# Generated by Django 4.2.4 on 2024-04-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdata',
            old_name='Market_Price',
            new_name='MarketPrice',
        ),
    ]
